# Generated by Django 4.0 on 2022-01-04 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст задания')),
                ('deadline', models.IntegerField(verbose_name='число дней на выполение задания')),
                ('created', models.DateTimeField(verbose_name='когда создано задание')),
            ],
            options={
                'db_table': 'homeworks',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='фамилия')),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='фамилия')),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='HomeworkResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.TextField(verbose_name='решение задания')),
                ('created', models.DateTimeField(verbose_name='время сдачи дз')),
                ('checked', models.BooleanField(default=False, verbose_name='проверено ли дз')),
                ('homework', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oop_3.homework')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oop_3.teacher')),
                ('solver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oop_3.student')),
            ],
            options={
                'db_table': 'solutions',
            },
        ),
    ]
